-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-11-04 00:39:12 SGT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE karyawan (
    id_karyawan          INTEGER NOT NULL,
    nama_karyawan        VARCHAR2(20) NOT NULL,
    no_hp                INTEGER NOT NULL,
    jabatan              VARCHAR2(20) NOT NULL,
    gaji                 INTEGER NOT NULL,
    alamat_karyawan      VARCHAR2(20) NOT NULL,
    email_karyawan       VARCHAR2(20) NOT NULL,
    karyawan_id_karyawan INTEGER NOT NULL,
    password_karyawan    VARCHAR2(20) NOT NULL
);

ALTER TABLE karyawan ADD CONSTRAINT karyawan_pk PRIMARY KEY ( id_karyawan );

CREATE TABLE kendaraan (
    vin_mobil            INTEGER NOT NULL,
    merek_mobil          VARCHAR2(20) NOT NULL,
    warna_mobil          VARCHAR2(20) NOT NULL,
    harga_mobil          VARCHAR2(20) NOT NULL,
    pabrikasi            VARCHAR2(20) NOT NULL,
    tahun_produksi       VARCHAR2(20) NOT NULL,
    pembeli_id_pembeli   INTEGER NOT NULL,
    karyawan_id_karyawan INTEGER NOT NULL
);

ALTER TABLE kendaraan ADD CONSTRAINT kendaraan_pk PRIMARY KEY ( vin_mobil );

CREATE TABLE mobil_keluarga (
    vin_mobil           INTEGER NOT NULL,
    kapasitas_penumpang VARCHAR2(20) NOT NULL
);

ALTER TABLE mobil_keluarga ADD CONSTRAINT mobil_keluarga_pk PRIMARY KEY ( vin_mobil );

CREATE TABLE mobil_sport (
    vin_mobil       INTEGER NOT NULL,
    fitur_kecepatan VARCHAR2(20) NOT NULL
);

ALTER TABLE mobil_sport ADD CONSTRAINT mobil_sport_pk PRIMARY KEY ( vin_mobil );

CREATE TABLE pembeli (
    id_pembeli       INTEGER NOT NULL,
    nama_pembeli     VARCHAR2(20) NOT NULL,
    no_hp            INTEGER NOT NULL,
    alamat_pembeli   VARCHAR2(20) NOT NULL,
    email_pembeli    VARCHAR2(20) NOT NULL,
    password_pembeli VARCHAR2(20) NOT NULL
);

ALTER TABLE pembeli ADD CONSTRAINT pembeli_pk PRIMARY KEY ( id_pembeli );

CREATE TABLE transaksi (
    no_transaksi         INTEGER NOT NULL,
    pembeli_id_pembeli   INTEGER,
    kendaraan_vin_mobil  INTEGER NOT NULL,
    tgl_transaki         DATE NOT NULL,
    metode_pembayaran    VARCHAR2(20) NOT NULL,
    status_pembayaran    VARCHAR2(20) NOT NULL,
    total_pembayaran     VARCHAR2(20) NOT NULL,
    id_pembeli           INTEGER,
    karyawan_id_karyawan INTEGER NOT NULL
);

ALTER TABLE transaksi ADD CONSTRAINT transaksi_pk PRIMARY KEY ( no_transaksi );

ALTER TABLE karyawan
    ADD CONSTRAINT karyawan_karyawan_fk FOREIGN KEY ( karyawan_id_karyawan )
        REFERENCES karyawan ( id_karyawan )
            ON DELETE CASCADE;

ALTER TABLE kendaraan
    ADD CONSTRAINT kendaraan_karyawan_fk FOREIGN KEY ( karyawan_id_karyawan )
        REFERENCES karyawan ( id_karyawan )
            ON DELETE CASCADE;

ALTER TABLE kendaraan
    ADD CONSTRAINT kendaraan_pembeli_fk FOREIGN KEY ( pembeli_id_pembeli )
        REFERENCES pembeli ( id_pembeli )
            ON DELETE CASCADE;

ALTER TABLE mobil_keluarga
    ADD CONSTRAINT mobil_keluarga_kendaraan_fk FOREIGN KEY ( vin_mobil )
        REFERENCES kendaraan ( vin_mobil );

ALTER TABLE mobil_sport
    ADD CONSTRAINT mobil_sport_kendaraan_fk FOREIGN KEY ( vin_mobil )
        REFERENCES kendaraan ( vin_mobil );

ALTER TABLE transaksi
    ADD CONSTRAINT transaksi_karyawan_fk FOREIGN KEY ( karyawan_id_karyawan )
        REFERENCES karyawan ( id_karyawan )
            ON DELETE CASCADE;

ALTER TABLE transaksi
    ADD CONSTRAINT transaksi_kendaraan_fk FOREIGN KEY ( kendaraan_vin_mobil )
        REFERENCES kendaraan ( vin_mobil )
            ON DELETE CASCADE;

ALTER TABLE transaksi
    ADD CONSTRAINT transaksi_pembeli_fk FOREIGN KEY ( pembeli_id_pembeli )
        REFERENCES pembeli ( id_pembeli )
            ON DELETE CASCADE;

--  ERROR: No Discriminator Column found in Arc FKArc_1 - constraint trigger for Arc cannot be generated 

--  ERROR: No Discriminator Column found in Arc FKArc_1 - constraint trigger for Arc cannot be generated



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             14
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   2
-- WARNINGS                                 0
